/*
 * Copyright (c) 2025 Adyen N.V.
 *
 * This file is open source and available under the MIT license. See the LICENSE file for more info.
 *
 * Created by ozgur on 2/9/2025.
 */

package com.adyen.checkout.core.common.localization

enum class CheckoutLocalizationKey {
    AWAIT_LOADING,
    CARD_NUMBER,
    CARD_NUMBER_INVALID,
    CARD_EXPIRY_DATE,
    CARD_EXPIRY_DATE_HINT,
    CARD_EXPIRY_DATE_INVALID,
    CARD_EXPIRY_DATE_INVALID_TOO_OLD,
    CARD_EXPIRY_DATE_INVALID_TOO_FAR_IN_THE_FUTURE,
    CARD_SECURITY_CODE,
    CARD_SECURITY_CODE_HINT_3_DIGITS,
    CARD_SECURITY_CODE_HINT_4_DIGITS,
    CARD_SECURITY_CODE_INVALID,
    CARD_HOLDER_NAME,
    CARD_HOLDER_NAME_INVALID,
    CARD_STORE_PAYMENT_METHOD,
    CARD_NUMBER_INVALID_UNSUPPORTED_BRAND,
    CARD_DUAL_BRAND_SELECTOR_TITLE,
    CARD_DUAL_BRAND_SELECTOR_DESCRIPTION,
    DROP_IN_MANAGE_FAVORITES_TITLE,
    DROP_IN_MANAGE_FAVORITES_CARDS_SECTION_TITLE,
    DROP_IN_MANAGE_FAVORITES_OTHERS_SECTION_TITLE,
    DROP_IN_MANAGE_FAVORITES_REMOVE,
    DROP_IN_MANAGE_FAVORITES_REMOVE_CONFIRMATION,
    DROP_IN_OTHER_PAYMENT_METHODS,
    DROP_IN_PAYMENT_METHOD_LIST_DESCRIPTION,
    DROP_IN_PAYMENT_METHOD_LIST_FAVORITES_SECTION_TITLE,
    DROP_IN_PAYMENT_METHOD_LIST_FAVORITES_SECTION_ACTION,
    DROP_IN_PAYMENT_METHOD_LIST_PAYMENT_OPTIONS_SECTION_TITLE,
    DROP_IN_PAYMENT_METHOD_LIST_PAYMENT_OPTIONS_SECTION_TITLE_WITH_FAVORITES,
    GENERAL_BACK,
    GENERAL_CANCEL,
    GENERAL_CLOSE,
    GENERAL_OPTIONAL,
    GENERAL_SEARCH_HINT,
    MBWAY_COUNTRY_CODE,
    MBWAY_INVALID_PHONE_NUMBER,
    MBWAY_PHONE_NUMBER,
    BLIK_CODE,
    BLIK_CODE_HINT,
    BLIK_CODE_INVALID,
    BLIK_HELPER_TEXT,
}
