complexity:
  active: true
  LongMethod:
    active: true
    threshold: 60
    excludes:
      - '**/test/**'
      - '**/androidTest/**'

naming:
  active: true
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - 'Composable'

style:
  active: true
  MagicNumber:
    active: true
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
  MaxLineLength:
    active: true
    maxLineLength: 120
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: false
    excludeRawStrings: true
    ignoreAnnotated:
      - Test
  UnusedPrivateMember:
    active: true
    ignoreAnnotated:
      - Preview

formatting:
  active: true
  android: true
  autoCorrect: true
  MaximumLineLength:
    active: true
    maxLineLength: 120
    ignoreBackTickedIdentifier: true
