name: Check PR

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build_and_test:
    name: Build and test
    permissions:
      contents: read
    uses: ./.github/workflows/build_and_test.yml
    secrets:
      gradle-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}
  validate_public_api:
    name: Validate public API
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/validate_public_api.yml
  verify_dependencies:
    name: Validate dependencies
    permissions:
      contents: read
    uses: ./.github/workflows/validate_dependencies.yml
  check_dependency_changes:
    name: Check dependency changes
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/check_dependency_changes.yml
