name: Check V5

on:
  push:
    branches:
      - 'v5'

permissions:
  contents: read

concurrency:
  group: 'v5'
  cancel-in-progress: true

jobs:
  build_and_test:
    name: Build and test
    uses: ./.github/workflows/build_and_test.yml
    secrets: inherit
