name: Check Release

# Every time we open a PR to merge develop into main branch for a release
on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
  check-release:
    # https://github.com/actions/virtual-environments/
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v4

      # Setup Java 17
      # https://github.com/marketplace/actions/setup-java-jdk
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: true

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Run gradlew check
      - name: Gradle check
        run: ./gradlew check --no-daemon
