name: Check V5

on:
  push:
    branches:
      - 'v5'

permissions:
  contents: read

concurrency:
  group: 'v5'
  cancel-in-progress: true

jobs:
  build_and_test:
    name: Build and test
    uses: ./.github/workflows/build_and_test.yml
    secrets:
      gradle-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}
