name: Check V5

on:
  push:
    branches:
      - 'v5'

concurrency:
  group: 'v5'
  cancel-in-progress: true

jobs:
  assemble:
    name: Assemble
    uses: ./.github/workflows/assemble.yml
  sonar_cloud:
    name: SonarCloud
    uses: ./.github/workflows/sonar_cloud.yml
    needs: assemble
    secrets: inherit
