name: Create github release

on:
  workflow_call:
    inputs:
      version-name:
        required: true
        type: string
      prerelease:
        required: true
        type: boolean
    secrets:
      github-token:
        required: true

permissions:
  contents: write

jobs:
  create_github_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      # Create a Github release with release notes.
      - name: Create Github release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
          VERSION_NAME: ${{ inputs.version-name }}
        with:
          token: ${{ env.GITHUB_TOKEN }}
          tag: ${{ env.VERSION_NAME }}
          commit: ${{ github.sha }}
          name: ${{ env.VERSION_NAME }}
          draft: true
          prerelease: ${{ inputs.prerelease }}
