name: Fetch Updated Release Notes File

on:
  workflow_call:
    inputs:
      version-name:
        description: "Version Name"
        required: true
        type: string
    outputs:
      updated-release-notes-filepath:
        description: "Filepath for the updated release notes file"
        value: ${{ jobs.fetch_updated_release_notes_file.outputs.updated-release-notes-filepath }}

jobs:
  fetch_updated_release_notes_file:
    name: Fetch Updated Release Notes File
    runs-on: ubuntu-latest
    outputs:
      updated-release-notes-filepath: ${{ steps.fetch_updated_release_notes_file.outputs.updated-release-notes-filepath }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: "release-notes"

      - name: Fetch filepath for updated release notes file
        id: fetch_updated_release_notes_file
        env:
          PROJECT_ROOT: ${{ github.workspace }}
          VERSION_NAME: ${{ inputs.version-name }}
        run: |
          chmod +x scripts/fetch_updated_release_notes_file.sh
          UPDATED_RELEASE_NOTES_FILEPATH=$(./scripts/fetch_updated_release_notes_file.sh $PROJECT_ROOT $VERSION_NAME)
          echo -e "updated-release-notes-filepath=$UPDATED_RELEASE_NOTES_FILEPATH" >> $GITHUB_OUTPUT
          echo -e $UPDATED_RELEASE_NOTES_FILEPATH
