name: Publish to Maven Central

on:
  workflow_dispatch:
    inputs:
      version-name:
        description: "Version name of the build"
        required: true
        type: string

  workflow_call:
    inputs:
      version-name:
        required: true
        type: string

permissions:
  contents: read

jobs:
  # This step should be removed when gradle plugin supports uploading to Central Portal
  drop_all_open_ossrh_repositories:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Drop all open OSSRH repositories
        env:
          SONATYPE_CENTRAL_PORTAL_USERNAME: ${{ secrets.SONATYPE_CENTRAL_PORTAL_USERNAME }}
          SONATYPE_CENTRAL_PORTAL_PASSWORD: ${{ secrets.SONATYPE_CENTRAL_PORTAL_PASSWORD }}
        run: |
          chmod +x scripts/drop_all_open_ossrh_repositories.py
          pip install requests toml
          python scripts/drop_all_open_ossrh_repositories.py

  publish_to_maven_central:
    needs: drop_all_open_ossrh_repositories
    runs-on:
      group: larger-runners
      labels: ubuntu-latest-8-cores

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Base64 decodes and pipes the GPG key content into the secret file
      - name: Prepare environment
        env:
          GPG_KEY_CONTENTS: ${{ secrets.GPG_KEY_CONTENTS }}
          SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
        run: |
          git fetch --unshallow
          sudo bash -c "echo '$GPG_KEY_CONTENTS' | base64 -d > '$SIGNING_SECRET_KEY_RING_FILE'"

      # Packages and publishes to Maven Central
      - name: Publish to Maven Central
        env:
          SONATYPE_CENTRAL_PORTAL_USERNAME: ${{ secrets.SONATYPE_CENTRAL_PORTAL_USERNAME }}
          SONATYPE_CENTRAL_PORTAL_PASSWORD: ${{ secrets.SONATYPE_CENTRAL_PORTAL_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
          VERSION_NAME: ${{ inputs.version-name }}
        run: ./gradlew publishReleasePublicationToSonatypeRepository --max-workers 1 --stacktrace -Pversion-name=$VERSION_NAME

  # This step should be removed when gradle plugin supports uploading to Central Portal
  move_repository_to_central_portal:
    needs: publish_to_maven_central
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # Moved the repository from OSSRH to Central Portal
      - name: Move repository to Central Portal
        env:
          SONATYPE_CENTRAL_PORTAL_USERNAME: ${{ secrets.SONATYPE_CENTRAL_PORTAL_USERNAME }}
          SONATYPE_CENTRAL_PORTAL_PASSWORD: ${{ secrets.SONATYPE_CENTRAL_PORTAL_PASSWORD }}
          PUBLISHING_TYPE: "portal_api"
        run: |
          chmod +x scripts/move_ossrh_repository_to_central_portal.py
          pip install requests toml
          python scripts/move_ossrh_repository_to_central_portal.py
