name: Finalize Release

# Every time the workflow is triggered
on:
  workflow_call:
    inputs:
      version-name:
        required: true
        type: string

jobs:
  publish_draft_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Publish Github release and the tag
      - name: Publish Github release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION_NAME: ${{ inputs.version-name }}
        with:
          token: ${{ env.GITHUB_TOKEN }}
          tag: ${{ env.VERSION_NAME }}
          allowUpdates: true
          updateOnlyUnreleased: true
          omitNameDuringUpdate: true
          omitBodyDuringUpdate: true
          draft: false
