name: Publish Docs

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write

jobs:

  publish-to-github-pages:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      # Setup Java 17
      # https://github.com/marketplace/actions/setup-java-jdk
      - name: Set up JDK
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          cache-read-only: true

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Generate kdocs
      - name: Generate Dokka HTML documentation
        run: ./gradlew dokkaHtmlMultiModule

      # Deploy to GitHub Pages
      - name: Deploy GitHub Pages
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        with:
          BRANCH: gh-pages
          FOLDER: build/docs/
