name: Test

on:
  workflow_call

permissions:
  contents: read

jobs:
  unit-test:
    name: Run unit tests
    runs-on:
      group: larger-runners
      labels: ubuntu-latest-8-cores

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run testDebugUnitTest
        run: ./gradlew testDebugUnitTest -Pstrip-resources=true

  lint:
    name: Run lint
    runs-on:
      group: larger-runners
      labels: ubuntu-latest-8-cores

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run lintDebug
        run: ./gradlew lintDebug -Pstrip-resources=true
