name: Test

on:
  workflow_call

jobs:
  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'gradle'

      - uses: actions/cache/restore@v3
        with:
          path: /home/runner/work/adyen-android/adyen-android
          key: cache-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run testDebugUnitTest
        run: ./gradlew testDebugUnitTest --no-daemon

  lint:
    name: Run lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'gradle'

      - uses: actions/cache/restore@v3
        with:
          path: /home/runner/work/adyen-android/adyen-android
          key: cache-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run lintDebug
        run: ./gradlew lintDebug --no-daemon
