name: Trigger Finalize Release

on:
  push:
    branches:
      - 'release-notes'

jobs:
  fetch_version_name:
    name: Fetch version name
    uses: ./.github/workflows/fetch_version_name_from_release_notes.yml

  trigger_finalize_release:
    name: Trigger Finalize Release on Release Branch
    runs-on: ubuntu-latest
    needs: fetch_version_name
    env:
      VERSION_NAME: ${{ needs.fetch_version_name.outputs.version-name }}

    steps:
      - name: Checkout to Release and Trigger Finalize Release
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/finalize_release.yml/dispatches \
          -d '{
            "ref":"release/${{ env.VERSION_NAME }}",
            "inputs": {
              "version-name": "${{ env.VERSION_NAME }}"
            }
          }'