name: Update verification metadata

on:
  push:
    branches:
      - 'renovate/android.gradle.plugin'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-verification-metadata:
    name: Update verification metadata
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.commits[0].message, '[skip update-verification-metadata]') }}

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          token: ${{ secrets.ADYEN_AUTOMATION_BOT_ACCESS_TOKEN }}

      - name: Set up JDK
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@748248ddd2a24f49513d8f472f81c3a07d4d50e1 # v4.4.4
        with:
          cache-read-only: true

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle update verification metadata
        run: ./gradlew --write-verification-metadata sha256 build

      - name: Commit
        run: |
          git config user.name "${{ secrets.ADYEN_AUTOMATION_BOT_USER }}"
          git config user.email "${{ secrets.ADYEN_AUTOMATION_BOT_NO_REPLY_EMAIL }}"
          git add .
          git diff-index --quiet HEAD || git commit -m "Update verification metadata
          
          [skip update-verification-metadata]"
          git push
