name: Update GitHub Release Notes

on:
  workflow_call:
    inputs:
      version-name:
        description: "Version Name"
        required: true
        type: string
      updated-release-notes-filepath:
        description: "Updated Release Notes Filepath"
        required: true
        type: string
jobs:
  update_release_notes:
    name: Update Release Notes
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: "release-notes"

      - name: Print updated release notes
        run: |
          cat ${{ inputs.updated-release-notes-filepath }}

      # Update Github release with the updated release notes
      - name: Update Github release notes
        id: update_github_release_notes
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION_NAME: ${{ inputs.version-name }}
          BODY_FILE: ${{ inputs.updated-release-notes-filepath }}
        with:
          token: ${{ env.GITHUB_TOKEN }}
          tag: ${{ env.VERSION_NAME }}
          allowUpdates: true
          updateOnlyUnreleased: true
          omitNameDuringUpdate: true
          draft: true
          bodyFile: ${{ env.BODY_FILE }}
