name: Validate public API

on:
  workflow_call

permissions:
  contents: read
  pull-requests: write

jobs:
  validate_public_api:
    name: Validate public API
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@ed408507eac070d1f99cc633dbcf757c94c7933a # v4
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          cache-read-only: true

      - name: Check public API
        run: |
          ( ./gradlew apiCheck --continue 2> "${{ github.workspace }}/api_changes.txt" ) || true
          bash ./scripts/process_api_changes.sh

      - name: Comment on PR
        # This step will only run on pull_request events.
        # PR information is only available when workflow gets triggered with pull_request event.
        # We also check that the PR is not from a fork, because this action will fail if it is.
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
        with:
          file-path: "${{ github.workspace }}/api_changes.md"
          comment-tag: api_changes
          mode: recreate

      - name: Check if successful
        run: |
          if [ -s api_changes.txt ]
          then
            # Fail workflow if there are API changes
            exit 1
          fi
