name: Validate dependencies

on:
  workflow_call:

permissions:
  contents: read

jobs:
  validate_dependencies_for_release_notes:
    runs-on: ubuntu-latest
    name: Validate newly added dependencies for release notes

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.14'

      - name: Validate dependencies for release notes
        run: |
          chmod +x scripts/validate_dependencies_for_release_notes.py
          python scripts/validate_dependencies_for_release_notes.py
