name: Validate dependencies

on:
  workflow_call:

permissions:
  contents: read

jobs:
  validate_dependencies_for_release_notes:
    runs-on: ubuntu-latest
    name: Validate newly added dependencies for release notes

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: '3.14'

      - name: Validate dependencies for release notes
        run: |
          chmod +x scripts/validate_dependencies_for_release_notes.py
          python scripts/validate_dependencies_for_release_notes.py
